import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class CityService{
    cityArray: string[] =[
        "Acre",
        "Afula",
        "Arad",
        "Ashdod",
        "Bat Yam",
        "Beersheba",
        "Beit She'an",
        "Bet Shemesh",
        "Bnei Brak",
        "Dimona",
        "Eilat",
        "Elad",
        "Giv'at Shmuel",
        "Givatayim",
        "Hadera",
        "Haifa",
        "Herzliya",
        "Hod HaSharon",
        "Holon",
        "Jerusalem",
        "Kafr Qasim",
        "Karmiel",
        "Kfar Saba",
        "Kfar Yona",
        "Qiryat Ata",
        "Qiryat Bialik",
        "Qiryat Gat",
        "Qiryat Motzkin",
        "Qiryat Ono",
        "Qiryat Shemona",
        "Qiryat Yam",
        "Lod",
        "Maalot Tarshiha",
        "Migdal",
        "Modin",
        "Nahariyya",
        "Nazareth",
        "Nesher",
        "Ness Ziona",
        "Netanya",
        "Netivot",
        "Netivot",
        "Ofakim",
        "Or Akiva",
        "Or Yehuda",
        "Petah Tikva",
        "Kalanswa",
        "Ranana",
        "Rahat",
        "Ramat Gan",
        "Ramat HaSharon",
        "Ramla",
        "Rehovot",
        "Rishon LeZion",
        "Rosh HaAyin",
        "Sakhnin",
        "Sderot",
        "Tamra",
        "Taibe",
        "Tel Aviv",
        "Tiberias",
        "Tira",
        "Tirat Carmel",
        "Yavne",

    ];
    static cityArray: any;

    returnCityArray() : string[]{
        return this.cityArray;
    }
}