import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class CityService{
    cityArray: string[] =[
        "Acre",
        "Afula",
        "Arad",
        "Arraba",
        "Ashdod",
        "Ashdod",
        "Baqa al-Gharbiyye",
        "Bat Yam",
        "Beersheba",
        "Beit She'an",
        "Beit Shemesh",
        "Bnei Brak",
        "Dimona",
        "Eilat",
        "El'ad",
        "Giv'at Shmuel",
        "Givatayim",
        "Hadera",
        "Haifa",
        "Herzliya",
        "Hod HaSharon",
        "Holon",
        "Jerusalem",
        "Kafr Qasim",
        "Karmiel",
        "Kfar Saba",
        "Kfar Yona",
        "Kiryat Ata",
        "Kiryat Bialik",
        "Kiryat Gat",
        "Kiryat Malakhi",
        "Kiryat Motzkin",
        "Kiryat Ono",
        "Kiryat Shmona",
        "Kiryat Yam",
        "Lod",
        "Ma'alot-Tarshiha",
        "Migdal HaEmek",
        "Modi'in",
        "Nahariya",
        "Nazareth",
        "Nesher",
        "Ness Ziona",
        "Netanya",
        "Netivot",
        "Netivot",
        "Ofakim",
        "Or Akiva",
        "Or Yehuda",
        "Petah Tikva",
        "Qalansawe",
        "Ra'anana",
        "Rahat",
        "Ramat Gan",
        "Ramat HaSharon",
        "Ramla",
        "Rehovot",
        "Rishon LeZion",
        "Rosh HaAyin",
        "Safed",
        "Sakhnin",
        "Sderot",
        "Shefa-'Amr",
        "Tamra",
        "Tayibe",
        "Tel Aviv",
        "Tiberias",
        "Tira",
        "Tirat Carmel",
        "Umm al-Fahm",
        "Yavne",
        "Yehud-Monosson",
        "Yokneam Illit"

    ];
}